import type { Place } from '@travely/shared/trip';

/**
 * Real coordinates and IANA zones for the places the demo catalogue uses. Codes follow
 * transport conventions: IATA for airports, UIC for stations, UN/LOCODE for ports and
 * coach stations.
 */
export const places = {
  CDG: {
    code: 'CDG',
    name: 'Charles de Gaulle',
    city: 'Paris',
    country: 'FR',
    lat: 49.0097,
    lon: 2.5479,
    tz: 'Europe/Paris',
  },
  JFK: {
    code: 'JFK',
    name: 'John F. Kennedy',
    city: 'New York',
    country: 'US',
    lat: 40.6413,
    lon: -73.7781,
    tz: 'America/New_York',
  },
  LIS: {
    code: 'LIS',
    name: 'Humberto Delgado',
    city: 'Lisbon',
    country: 'PT',
    lat: 38.7742,
    lon: -9.1342,
    tz: 'Europe/Lisbon',
  },
  LHR: {
    code: 'LHR',
    name: 'Heathrow',
    city: 'London',
    country: 'GB',
    lat: 51.47,
    lon: -0.4543,
    tz: 'Europe/London',
  },
  PLY: {
    code: '87686006',
    name: 'Gare de Lyon',
    city: 'Paris',
    country: 'FR',
    lat: 48.8443,
    lon: 2.3743,
    tz: 'Europe/Paris',
  },
  LPD: {
    code: '87723197',
    name: 'Part-Dieu',
    city: 'Lyon',
    country: 'FR',
    lat: 45.7605,
    lon: 4.8595,
    tz: 'Europe/Paris',
  },
  MCN: {
    code: '87686667',
    name: 'Le Creusot TGV',
    city: 'Le Creusot',
    country: 'FR',
    lat: 46.7644,
    lon: 4.4534,
    tz: 'Europe/Paris',
  },
  MAC: {
    code: '87713040',
    name: 'Macon Loche TGV',
    city: 'Macon',
    country: 'FR',
    lat: 46.2758,
    lon: 4.8025,
    tz: 'Europe/Paris',
  },
  PNO: {
    code: '87271007',
    name: 'Gare du Nord',
    city: 'Paris',
    country: 'FR',
    lat: 48.8809,
    lon: 2.3553,
    tz: 'Europe/Paris',
  },
  STP: {
    code: '70154100',
    name: 'St Pancras',
    city: 'London',
    country: 'GB',
    lat: 51.5308,
    lon: -0.1257,
    tz: 'Europe/London',
  },
  FRMRS: {
    code: 'FRMRS',
    name: 'Port de la Joliette',
    city: 'Marseille',
    country: 'FR',
    lat: 43.3047,
    lon: 5.3661,
    tz: 'Europe/Paris',
  },
  FRBIA: {
    code: 'FRBIA',
    name: 'Port de Bastia',
    city: 'Bastia',
    country: 'FR',
    lat: 42.7028,
    lon: 9.4509,
    tz: 'Europe/Paris',
  },
  FRBER: {
    code: 'FRBER',
    name: 'Bercy Seine',
    city: 'Paris',
    country: 'FR',
    lat: 48.8388,
    lon: 2.3826,
    tz: 'Europe/Paris',
  },
  NLSLD: {
    code: 'NLSLD',
    name: 'Sloterdijk',
    city: 'Amsterdam',
    country: 'NL',
    lat: 52.3894,
    lon: 4.8375,
    tz: 'Europe/Amsterdam',
  },
  BEBRU: {
    code: 'BEBRU',
    name: 'Bruxelles-Nord',
    city: 'Brussels',
    country: 'BE',
    lat: 50.8599,
    lon: 4.3607,
    tz: 'Europe/Brussels',
  },
} as const satisfies Record<string, Place>;

export type PlaceKey = keyof typeof places;
