import operatorsData from "../data/operators.json";
import { Mode } from "./types";

/**
 * Who runs a service, and how to recognise it from what a traveller types. The data is
 * bundled (`data/operators.json`, regenerated by `scripts/build-operators.ts`) rather than
 * fetched: recognising "AF" as Air France has to happen on the keystroke, offline, before
 * any provider is called.
 *
 * Everything here is pure. The app resolves a logo through `airlineLogoUrl`, which is a
 * URL template, not a request.
 */

export type OperatorMode = "flight" | "train" | "ferry" | "bus";

export interface Operator {
  /** What lands in `LegIdentity.operator`: "AF", "SNCF", "DEMO". At most 8 ASCII bytes. */
  code: string;
  name: string;
  mode: OperatorMode;
  country: string;
  /** Airlines only, and always equal to `code` when set. */
  iata?: string;
  icao?: string;
  /** Brands and service names a ticket may print instead of the operator: "TGV", "ICE". */
  aliases?: readonly string[];
  /** At most five characters to draw when no logo exists, with the ink to draw them in. */
  wordmark?: string;
  brand?: string;
}

/** `[iata, icao, name, country]`. */
type FlightTuple = [string, string, string, string];
/** `[code, name, mode, country, aliases, wordmark, brand]`. */
type CuratedTuple = [string, string, OperatorMode, string, string[], string, string];

const data = operatorsData as unknown as {
  source: string;
  licence: string;
  generatedAt: string;
  flights: FlightTuple[];
  curated: CuratedTuple[];
};

export const OPERATORS_SOURCE = data.source;
export const OPERATORS_LICENCE = data.licence;

function fromFlightTuple([iata, icao, name, country]: FlightTuple): Operator {
  return { code: iata, name, mode: "flight", country, iata, icao };
}

function fromCuratedTuple([
  code,
  name,
  mode,
  country,
  aliases,
  wordmark,
  brand,
]: CuratedTuple): Operator {
  return {
    code,
    name,
    mode,
    country,
    aliases,
    ...(wordmark ? { wordmark } : {}),
    ...(brand ? { brand } : {}),
  };
}

/** Every operator the app knows, curated ones first so they win an ambiguous code. */
export const OPERATORS: readonly Operator[] = [
  ...data.curated.map(fromCuratedTuple),
  ...data.flights.map(fromFlightTuple),
];

const DIACRITICS_RE = /[\u0300-\u036f]/g;
const NON_ALPHANUMERIC_RE = /[^A-Z0-9&]/g;
const WHITESPACE_RE = /\s+/g;

/** Uppercase, unaccented, single-spaced: what a name is compared as. */
export function foldText(value: string): string {
  return value
    .normalize("NFD")
    .replace(DIACRITICS_RE, "")
    .toUpperCase()
    .replace(WHITESPACE_RE, " ")
    .trim();
}

/** `foldText` with every separator dropped: what a code or a typed reference compares as. */
export function foldCode(value: string): string {
  return foldText(value).replace(NON_ALPHANUMERIC_RE, "");
}

interface IndexedOperator {
  operator: Operator;
  code: string;
  icao: string;
  name: string;
  aliases: string[];
}

const INDEX: readonly IndexedOperator[] = OPERATORS.map((operator) => ({
  operator,
  code: foldCode(operator.code),
  icao: operator.icao ? foldCode(operator.icao) : "",
  name: foldText(operator.name),
  aliases: (operator.aliases ?? []).map(foldCode),
}));

/**
 * Every string that can stand for an operator at the head of a reference, mapped to the
 * operators that answer to it. Codes are registered before aliases, so "FR" is Ryanair
 * rather than whichever operator happens to list it as a brand.
 */
const TOKENS = new Map<string, Operator[]>();
let longestToken = 2;

function registerToken(token: string, operator: Operator): void {
  if (token.length < 2) return;
  const current = TOKENS.get(token);
  if (current) {
    if (!current.includes(operator)) current.push(operator);
  } else {
    TOKENS.set(token, [operator]);
  }
  if (token.length > longestToken) longestToken = token.length;
}

for (const entry of INDEX) registerToken(entry.code, entry.operator);
for (const entry of INDEX) if (entry.icao) registerToken(entry.icao, entry.operator);
for (const entry of INDEX) for (const alias of entry.aliases) registerToken(alias, entry.operator);

const MODE_NAMES: Record<Mode, OperatorMode> = {
  [Mode.Flight]: "flight",
  [Mode.Train]: "train",
  [Mode.Ferry]: "ferry",
  [Mode.Bus]: "bus",
};

/** The numeric travel `Mode` as the string an `Operator` carries. */
export function operatorModeOf(mode: Mode): OperatorMode {
  return MODE_NAMES[mode];
}

export interface SearchOperatorsOptions {
  mode?: OperatorMode;
  limit?: number;
}

/**
 * Ranking, best first: an exact code, a code prefix, a name prefix, a name substring, an
 * alias. Ties break on the shorter name, because a mainline carrier is rarely the one with
 * the longest legal name, and then on the code so the order never depends on input order.
 */
const Tier = {
  ExactCode: 0,
  CodePrefix: 1,
  NamePrefix: 2,
  NameSubstring: 3,
  Alias: 4,
  None: 5,
} as const;
type Tier = (typeof Tier)[keyof typeof Tier];

function tierOf(entry: IndexedOperator, text: string, code: string): Tier {
  if (code.length > 0) {
    if (entry.code === code || entry.icao === code) return Tier.ExactCode;
    if (entry.code.startsWith(code) || (entry.icao !== "" && entry.icao.startsWith(code))) {
      return Tier.CodePrefix;
    }
  }
  if (text.length > 0) {
    if (entry.name.startsWith(text)) return Tier.NamePrefix;
    if (entry.name.includes(text)) return Tier.NameSubstring;
  }
  if (code.length > 0 && entry.aliases.some((alias) => alias.startsWith(code))) return Tier.Alias;
  return Tier.None;
}

export function searchOperators(
  query: string,
  options: SearchOperatorsOptions = {},
): Operator[] {
  const text = foldText(query);
  if (text.length === 0) return [];
  const code = foldCode(query);
  const limit = options.limit ?? 6;

  const matches: { entry: IndexedOperator; tier: Tier }[] = [];
  for (const entry of INDEX) {
    if (options.mode && entry.operator.mode !== options.mode) continue;
    const tier = tierOf(entry, text, code);
    if (tier !== Tier.None) matches.push({ entry, tier });
  }

  matches.sort(
    (a, b) =>
      a.tier - b.tier ||
      a.entry.name.length - b.entry.name.length ||
      a.entry.code.localeCompare(b.entry.code),
  );

  return matches.slice(0, limit).map((match) => match.entry.operator);
}

/** The operator behind an exact code, ICAO code or alias. */
export function findOperator(code: string, mode?: OperatorMode): Operator | undefined {
  const candidates = TOKENS.get(foldCode(code));
  if (!candidates) return undefined;
  if (!mode) return candidates[0];
  return candidates.find((operator) => operator.mode === mode) ?? undefined;
}

export interface OperatorReference {
  operator: Operator;
  /** The service number with the operator prefix removed: "AF 1180" gives "1180". */
  number: string;
}

const REFERENCE_TAIL_RE = /^\d{1,5}[A-Z]?$/;

/**
 * Split a typed reference into the operator that runs it and the number itself. Codes are
 * not all alphabetic ("U2", "9F") and brands are not all codes ("TGV6231"), so the split
 * is found by trying every prefix long to short against the token index rather than by
 * cutting at the first digit.
 */
export function operatorFromReference(
  reference: string,
  options: { mode?: OperatorMode } = {},
): OperatorReference | null {
  const folded = foldCode(reference);
  if (folded.length < 3) return null;

  const longest = Math.min(longestToken, folded.length - 1);
  for (let length = longest; length >= 2; length -= 1) {
    const tail = folded.slice(length);
    if (!REFERENCE_TAIL_RE.test(tail)) continue;
    const candidates = TOKENS.get(folded.slice(0, length));
    if (!candidates) continue;
    const operator = options.mode
      ? candidates.find((entry) => entry.mode === options.mode)
      : candidates[0];
    if (operator) return { operator, number: tail };
  }
  return null;
}

/**
 * Airline logos come from avs.io, the free CDN the flight-tracking apps use: no key, no
 * rate limit worth the name, and a transparent PNG keyed on the IATA designator. A miss is
 * a 404, which `OperatorMark` treats as "draw the lettermark instead".
 *
 * The alternative is AirHex (`https://content.airhex.com/content/logos/airlines_<iata>_
 * 100_100_s.png`), which `adapters/flight.ts` still uses for the logo the proxy attaches
 * to a leg; it covers slightly fewer carriers and is slower from Europe.
 */
export function airlineLogoUrl(iata: string): string {
  return `https://pics.avs.io/200/200/${foldCode(iata)}.png`;
}

/**
 * The logo for an operator, or `undefined` when it has none and should be drawn as a
 * wordmark or a lettermark. Rail, ferry and bus operators deliberately have none: their
 * marks are trademarks we do not redistribute.
 */
export function operatorLogoUrl(operator: Operator): string | undefined {
  return operator.mode === "flight" && operator.iata ? airlineLogoUrl(operator.iata) : undefined;
}

/**
 * The number as the operator prints it alone, with the code stripped when the reference
 * repeats it: "AF1180" under "AF" is "1180", while a train's "6231" under "SNCF" is
 * already bare. Flight identities carry the full reference and rail identities do not, so
 * anything matching on what a traveller types has to compare both.
 */
export function bareServiceNumber(operator: string, number: string): string {
  const code = foldCode(operator);
  const folded = foldCode(number);
  return code.length > 0 && folded.length > code.length && folded.startsWith(code)
    ? folded.slice(code.length)
    : folded;
}

/**
 * Does what has been typed so far stand for this service? Providers only ever resolve an
 * exact number, so this is what every instant suggestion matches on instead: a prefix of
 * the bare number ("11" for AF1180) or of the full reference ("AF11"), because a boarding
 * pass prints one and a departure board the other.
 */
export function serviceNumberMatchesPrefix(
  operator: string,
  number: string,
  prefix: string,
): boolean {
  const wanted = foldCode(prefix);
  if (wanted.length === 0) return true;
  const bare = bareServiceNumber(operator, number);
  return (
    bare.startsWith(wanted) ||
    foldCode(number).startsWith(wanted) ||
    `${foldCode(operator)}${bare}`.startsWith(wanted)
  );
}
